import { z } from 'zod';

// Body validation
export const CreateExaminationBody = z
  .object({
    zoba: z.string(),
    subZoba: z.string(),
    address: z.string(),
    bloodPressureDiastolic: z.string(),
    bloodPressureSystolic: z.string(),
    bloodSugar: z.string(),
    heartRate: z.string(),
    latitude: z.string(),
    localDistrict: z.string(),
    longitude: z.string(),
    oxygenSaturation: z.string(),
    respiratoryRate: z.string(),
    temperature: z.string(),
    hasFever: z.boolean(),
    hasHeadache: z.boolean(),
    hasDizziness: z.boolean(),
    hasNausea: z.boolean(),
    hasFatigue: z.boolean(),
    hasWeightLoss: z.boolean(),
    hasSweating: z.boolean(),
    hasCough: z.boolean(),
    hasShortnessOfBreath: z.boolean(),
    hasSoreThroat: z.boolean(),
    hasChestPain: z.boolean(),
    hasVomiting: z.boolean(),
    hasDiarrhea: z.boolean(),
    hasStomachPain: z.boolean(),
    hasConstipation: z.boolean(),
    hasAppetiteLoss: z.boolean(),
    hasMusclePain: z.boolean(),
    hasJointPain: z.boolean(),
    hasBackPain: z.boolean(),
    hasNeckPain: z.boolean(),
    hasNumbness: z.boolean(),
    hasSeizures: z.boolean(),
    hasDifficultySpeaking: z.boolean(),
    hasRash: z.boolean(),
    hasItching: z.boolean(),
    hasBruising: z.boolean(),
    hasPainfulUrination: z.boolean(),
    hasFrequentUrination: z.boolean(),
    hasBloodInUrine: z.boolean(),
    hasEarPain: z.boolean(),
    hasHearingLoss: z.boolean(),
    hasNasalCongestion: z.boolean(),
    hasRunnyNose: z.boolean(),
    hasSneezing: z.boolean(),
    hasEyePain: z.boolean(),
    hasRedEye: z.boolean(),
    hasBlurredVision: z.boolean(),
    hasVisionLoss: z.boolean(),
  })
  .strict();

export type CreateExaminationDto = z.infer<typeof CreateExaminationBody>;
